name: jpl_moshier_ephemeris_dart_example
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  ffi: ^2.2.0
  flutter:
    sdk: flutter
  jpl_moshier_ephemeris_dart:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
